#!/bin/bash

# Display available block devices in /dev
echo "Available block devices in /dev:"
ls /dev/sd* /dev/vd* 2>/dev/null

# Prompt the user to input the path to the disk
read -p "Please enter the path to the disk (e.g., /dev/vda): " DISK

# Validate the user input
if [ ! -b "$DISK" ]; then
    echo "Invalid input: $DISK is not a valid block device."
    exit 1
fi

echo "Using disk: $DISK"


parted $DISK mklabel GPT

parted $DISK mkpart primary 2MiB 512MiB

parted $DISK mkpart primary 512MiB 2560MiB

parted $DISK mkpart primary 2560MiB 100%


cryptsetup --verify-passphrase -v luksFormat "$DISK"3
cryptsetup open "$DISK"3 enc

mkfs.vfat -n boot "$DISK"1
mkswap "$DISK"2
swapon "$DISK"2
mkfs.btrfs /dev/mapper/enc

mount -t btrfs /dev/mapper/enc /mnt

# We first create the subvolumes outlined above:
btrfs subvolume create /mnt/root
btrfs subvolume create /mnt/home
btrfs subvolume create /mnt/nix
btrfs subvolume create /mnt/persist
btrfs subvolume create /mnt/log

# We then take an empty *readonly* snapshot of the root subvolume,
# which we'll eventually rollback to on every boot.
btrfs subvolume snapshot -r /mnt/root /mnt/root-blank

umount /mnt

mount -o subvol=root,compress=zstd,noatime /dev/mapper/enc /mnt

mkdir /mnt/home
mount -o subvol=home,compress=zstd,noatime /dev/mapper/enc /mnt/home

mkdir /mnt/nix
mount -o subvol=nix,compress=zstd,noatime /dev/mapper/enc /mnt/nix

mkdir /mnt/persist
mount -o subvol=persist,compress=zstd,noatime /dev/mapper/enc /mnt/persist

mkdir -p /mnt/var/log
mount -o subvol=log,compress=zstd,noatime /dev/mapper/enc /mnt/var/log

# don't forget this!
mkdir /mnt/boot
mount "$DISK"1 /mnt/boot

nixos-generate-config --root /mnt

